### ISSUE TITLE
design update for main page.

### ISSUE THREAD

**Issue by anugcodes** [lokeshvasnik/Modern-Notes#2]
we can simply move the theme switcher button and time to the left column , above the create new note button.
this way it will result in a two column design which will easier to manage for different devices and making the website more responsive.
also resulting in more space for taking notes.

what do you think? @lokeshvasnik

**Comment by lokeshvasnik** [comment]
Umm...  Amazing idea

**Comment by lokeshvasnik** [comment]
@anugcodes  If you want to give it a try go for it

**Comment by anugcodes** [comment]
> @anugcodes  If you want to give it a try go for it

Sure @lokeshvasnik  i can do it. But I may require some time. You can assign me the task.

**Comment by lokeshvasnik** [comment]
Great
